---
# see bigdft.org for installation instructions
- name: Install bigdft dependencies
  become: true
  become_user: "{{ root_user }}"
  apt:
    name:
      - gfortran
      - openmpi-common
      - openmpi-bin
      - libopenmpi-dev
      - libblacs-mpi-dev
      - libscalapack-mpi-dev
      - libblas-dev
      - liblapack-dev
      - libnetcdf-dev
      - libopenbabel-dev
      - cmake

- name: Get bigdft source
  get_url:
    url: "{{ bigdft_url }}"
    dest: "{{ bigdft_code_folder }}/{{ bigdft_src_archive }}"
  register: bigdft_download
  
- name: Extract bigdft source
  unarchive:
    src: "{{ bigdft_download.dest }}"
    dest: "{{ bigdft_code_folder }}"
    remote_src: true

- name: Create build dir
  file:
    path: "{{ bigdft_topdir }}/build"
    state: directory

- name: This is to remove problematic patches in release 1.8.3. Remove it later
  replace:
    path: "{{ bigdft_topdir }}/bigdft.modules"
    regexp: "^.*doxygen.*$"

# - name: Copy rcfile
#   template:
#     src: rcfile-quantum-mobile.rc
#     dest: "{{ bigdft_topdir }}/rcfiles"

- name: Make bigdft executables
  command: "../Installer.py build -y -a babel -f ../rcfiles/ubuntu_MPI.rc -v"
  # shell: "../Installer.py build -y -a babel -f ../rcfiles/rcfile-quantum-mobile.rc -v"
  args:
    chdir: "{{ bigdft_topdir }}/build"
    creates: "{{ bigdft_topdir }}/build/install/bin/bigdft"
  register: bigdft_make

- import_tasks: tests.yml
#  when: bigdft_make.changed and run_tests is defined and run_tests

- name: "Put a line in ~/.profile to add bigdft to the path"
  lineinfile:
    path: "${HOME}/.profile"
    line: "export PATH=${PATH}:{{ bigdft_topdir }}/build/install/bin"

- name: "Put a line in ~/.profile to add bigdft to the ld_library_path"
  lineinfile:
    path: "${HOME}/.profile"
    line: "export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:{{ bigdft_topdir }}/build/install/lib"

- include_role:
    name: release_notes
  vars:
    section: "bigdft"
    option: "version"
    value: "{{ bigdft_version }}"
  when: release_notes is defined and release_notes

- include_role:
    name: release_notes
  vars:
    section: "bigdft"
    option: "usage"
    value: >-
      bigdft is compiled and installed in {{ bigdft_topdir }}/build/install.
      simply run 'bigdft'
  when: release_notes is defined and release_notes
